export const mockTree = {
  name: '知识库',
  domain: 'IT',
  children: [
    {
      name: '编程语言',
      domain: 'IT',
      children: [
        { name: 'Rust 入门指南.md', path: 'IT/编程语言/Rust 入门指南.md', is_entry: true, domain: 'IT' },
        { name: 'Python 进阶.md', path: 'IT/编程语言/Python 进阶.md', is_entry: true, domain: 'IT' },
        { name: 'TypeScript 实战.md', path: 'IT/编程语言/TypeScript 实战.md', is_entry: true, domain: 'IT' },
      ],
    },
    {
      name: '系统架构',
      domain: 'IT',
      children: [
        { name: '微服务设计模式.md', path: 'IT/系统架构/微服务设计模式.md', is_entry: true, domain: 'IT' },
        { name: '分布式系统原理.md', path: 'IT/系统架构/分布式系统原理.md', is_entry: true, domain: 'IT' },
      ],
    },
    {
      name: '人工智能',
      domain: 'AI',
      children: [
        { name: '机器学习基础.md', path: 'AI/人工智能/机器学习基础.md', is_entry: true, domain: 'AI' },
        { name: '深度学习实战.md', path: 'AI/人工智能/深度学习实战.md', is_entry: true, domain: 'AI' },
        { name: '大模型应用.md', path: 'AI/人工智能/大模型应用.md', is_entry: true, domain: 'AI' },
      ],
    },
    {
      name: '数学基础',
      domain: 'Math',
      children: [
        { name: '线性代数.md', path: 'Math/数学基础/线性代数.md', is_entry: true, domain: 'Math' },
        { name: '概率论.md', path: 'Math/数学基础/概率论.md', is_entry: true, domain: 'Math' },
      ],
    },
  ],
}

const makeBody = (title, sections) => [
  `# ${title}`,
  '',
  ...sections,
].join('\n')

export const mockEntries = {
  'IT/编程语言/Rust 入门指南.md': {
    title: 'Rust 入门指南',
    domain: 'IT',
    level: 'L1',
    status: 'published',
    quality_score: 0.92,
    version: '1.2.0',
    source: 'pdf',
    tags: ['rust', '系统编程', '内存安全'],
    body_markdown: makeBody('Rust 入门指南', [
      '## 简介',
      '',
      'Rust 是一种系统级编程语言，以**安全性**、**并发性**和**性能**著称。',
      '',
      '## 核心特性',
      '',
      '### 所有权系统',
      '',
      '```rust',
      'fn main() {',
      '    let s1 = String::from("hello");',
      '    let s2 = s1;',
      '    println!("{}", s2);',
      '}',
      '```',
      '',
      '### 借用检查器',
      '',
      '```rust',
      'fn calculate_length(s: &String) -> usize {',
      '    s.len()',
      '}',
      '```',
      '',
      '## 学习路线',
      '',
      '| 阶段 | 内容 | 预计时间 |',
      '|------|------|----------|',
      '| 入门 | 变量、基本类型、函数 | 1 周 |',
      '| 进阶 | 所有权、生命周期、泛型 | 2 周 |',
      '| 精通 | 异步编程、unsafe、宏 | 3 周 |',
    ]),
    related: ['IT/系统架构/微服务设计模式.md', 'AI/人工智能/机器学习基础.md'],
    backlinks: [],
  },

  'IT/编程语言/Python 进阶.md': {
    title: 'Python 进阶',
    domain: 'IT',
    level: 'L1',
    status: 'published',
    quality_score: 0.88,
    version: '1.1.0',
    tags: ['python', '进阶', '高级特性'],
    body_markdown: makeBody('Python 进阶', [
      '## 装饰器',
      '',
      '装饰器是高阶函数，用于修改函数或类的行为。',
      '',
      '```python',
      'def my_decorator(func):',
      '    def wrapper(*args, **kwargs):',
      '        print("Before")',
      '        result = func(*args, **kwargs)',
      '        print("After")',
      '        return result',
      '    return wrapper',
      '',
      '@my_decorator',
      'def say_hello():',
      '    print("Hello!")',
      '```',
      '',
      '## 上下文管理器',
      '',
      '```python',
      'class FileManager:',
      '    def __init__(self, filename):',
      '        self.filename = filename',
      '',
      '    def __enter__(self):',
      '        self.file = open(self.filename, "r")',
      '        return self.file',
      '',
      '    def __exit__(self, exc_type, exc_val, exc_tb):',
      '        self.file.close()',
      '',
      'with FileManager("test.txt") as f:',
      '    content = f.read()',
      '```',
      '',
      '## 异步编程',
      '',
      '```python',
      'import asyncio',
      '',
      'async def main():',
      '    print("Hello")',
      '    await asyncio.sleep(1)',
      '    print("World")',
      '',
      'asyncio.run(main())',
      '```',
    ]),
    related: ['IT/编程语言/TypeScript 实战.md'],
    backlinks: [],
  },

  'IT/编程语言/TypeScript 实战.md': {
    title: 'TypeScript 实战',
    domain: 'IT',
    level: 'L1',
    status: 'published',
    quality_score: 0.85,
    version: '1.0.0',
    tags: ['typescript', 'javascript', '类型系统'],
    body_markdown: makeBody('TypeScript 实战', [
      '## 类型系统',
      '',
      'TypeScript 提供静态类型检查，在编译时捕获错误。',
      '',
      '```typescript',
      'interface User {',
      '  id: number;',
      '  name: string;',
      '  email?: string;',
      '}',
      '',
      'function greet(user: User): string {',
      '  return `Hello, ${user.name}!`;',
      '}',
      '```',
      '',
      '## 泛型',
      '',
      '```typescript',
      'function identity<T>(arg: T): T {',
      '  return arg;',
      '}',
      '',
      'const num = identity<number>(42);',
      'const str = identity("hello");',
      '```',
      '',
      '## 高级类型',
      '',
      '| 类型 | 说明 |',
      '|------|------|',
      '| Union | 联合类型 |',
      '| Intersection | 交叉类型 |',
      '| Conditional | 条件类型 |',
      '| Mapped | 映射类型 |',
    ]),
    related: ['IT/编程语言/Python 进阶.md', 'IT/系统架构/微服务设计模式.md'],
    backlinks: [],
  },

  'IT/系统架构/微服务设计模式.md': {
    title: '微服务设计模式',
    domain: 'IT',
    level: 'L2',
    status: 'published',
    quality_score: 0.88,
    version: '1.0.0',
    tags: ['微服务', '架构', '设计模式'],
    body_markdown: makeBody('微服务设计模式', [
      '## 概述',
      '',
      '微服务架构将大型应用拆分为多个小型、独立的服务。',
      '',
      '## 核心模式',
      '',
      '### 1. API Gateway',
      '',
      '作为所有客户端的单一入口，负责请求路由和协议转换。',
      '',
      '### 2. 服务发现',
      '',
      '客户端通过服务注册中心发现服务实例。',
      '',
      '### 3. Circuit Breaker',
      '',
      '```',
      '请求 -> Circuit Breaker -> 服务',
      '         |',
      '      熔断打开',
      '```',
      '',
      '## 最佳实践',
      '',
      '1. **单一职责** - 每个服务只负责一件事',
      '2. **独立部署** - 服务可以独立版本化和部署',
      '3. **自动化** - 使用 CI/CD 自动化部署流程',
    ]),
    related: ['IT/编程语言/Rust 入门指南.md', 'AI/人工智能/机器学习基础.md'],
    backlinks: [],
  },

  'IT/系统架构/分布式系统原理.md': {
    title: '分布式系统原理',
    domain: 'IT',
    level: 'L2',
    status: 'published',
    quality_score: 0.90,
    version: '1.0.0',
    tags: ['分布式', '一致性', 'CAP'],
    body_markdown: makeBody('分布式系统原理', [
      '## CAP 定理',
      '',
      '分布式系统最多只能同时满足以下两个特性：',
      '',
      '| 特性 | 说明 |',
      '|------|------|',
      '| Consistency | 一致性 |',
      '| Availability | 可用性 |',
      '| Partition tolerance | 分区容错性 |',
      '',
      '## 一致性模型',
      '',
      '### 强一致性',
      '',
      '所有节点在同一时刻看到相同的数据。',
      '',
      '### 最终一致性',
      '',
      '系统保证在没有新更新的情况下，最终所有副本将一致。',
      '',
      '## 共识算法',
      '',
      '- **Raft** - 易于理解的一致性算法',
      '- **Paxos** - 经典的分布式共识协议',
      '- **PBFT** - 实用拜占庭容错算法',
    ]),
    related: ['IT/系统架构/微服务设计模式.md'],
    backlinks: [],
  },

  'AI/人工智能/机器学习基础.md': {
    title: '机器学习基础',
    domain: 'AI',
    level: 'L1',
    status: 'published',
    quality_score: 0.85,
    version: '1.0.0',
    tags: ['机器学习', '监督学习', '神经网络'],
    body_markdown: makeBody('机器学习基础', [
      '## 什么是机器学习？',
      '',
      '机器学习是人工智能的一个分支，通过**数据**和**算法**让计算机系统能够自动改进性能。',
      '',
      '## 核心概念',
      '',
      '### 监督学习',
      '',
      '利用标记数据训练模型：',
      '',
      '- 分类（Classification）',
      '- 回归（Regression）',
      '',
      '### 无监督学习',
      '',
      '从未标记数据中发现模式：',
      '',
      '- 聚类（Clustering）',
      '- 降维（Dimensionality Reduction）',
      '',
      '## 常用算法',
      '',
      '| 算法 | 类型 | 适用场景 |',
      '|------|------|----------|',
      '| 线性回归 | 监督学习 | 预测连续值 |',
      '| 决策树 | 监督学习 | 分类/回归 |',
      '| K-Means | 无监督学习 | 聚类分析 |',
      '| 神经网络 | 监督学习 | 复杂模式识别 |',
    ]),
    related: ['AI/人工智能/深度学习实战.md', 'IT/编程语言/Rust 入门指南.md'],
    backlinks: [],
  },

  'AI/人工智能/深度学习实战.md': {
    title: '深度学习实战',
    domain: 'AI',
    level: 'L1',
    status: 'published',
    quality_score: 0.82,
    version: '1.0.0',
    tags: ['深度学习', '神经网络', 'PyTorch'],
    body_markdown: makeBody('深度学习实战', [
      '## 神经网络基础',
      '',
      '深度学习使用多层神经网络来学习数据的分层表示。',
      '',
      '```python',
      'import torch',
      'import torch.nn as nn',
      '',
      'class SimpleNet(nn.Module):',
      '    def __init__(self):',
      '        super().__init__()',
      '        self.fc1 = nn.Linear(784, 128)',
      '        self.fc2 = nn.Linear(128, 10)',
      '',
      '    def forward(self, x):',
      '        x = torch.relu(self.fc1(x))',
      '        return self.fc2(x)',
      '```',
      '',
      '## 经典架构',
      '',
      '| 架构 | 年份 | 主要应用 |',
      '|------|------|----------|',
      '| LeNet | 1998 | 手写数字识别 |',
      '| AlexNet | 2012 | 图像分类 |',
      '| ResNet | 2015 | 深度残差网络 |',
      '| Transformer | 2017 | NLP 里程碑 |',
    ]),
    related: ['AI/人工智能/机器学习基础.md', 'AI/人工智能/大模型应用.md'],
    backlinks: [],
  },

  'AI/人工智能/大模型应用.md': {
    title: '大模型应用',
    domain: 'AI',
    level: 'L2',
    status: 'published',
    quality_score: 0.78,
    version: '1.0.0',
    tags: ['LLM', 'GPT', 'Prompt Engineering'],
    body_markdown: makeBody('大模型应用', [
      '## 大语言模型概述',
      '',
      '大语言模型（LLM）是基于Transformer架构的海量参数神经网络。',
      '',
      '## Prompt Engineering',
      '',
      '### 零样本提示',
      '',
      '```',
      '请将以下文本翻译成中文：',
      'The quick brown fox jumps over the lazy dog.',
      '```',
      '',
      '### 少样本提示',
      '',
      '提供几个示例帮助模型理解任务。',
      '',
      '## 应用场景',
      '',
      '- **文本生成** - 文章、代码、对话',
      '- **知识问答** - RAG 检索增强',
      '- **代码助手** - Copilot 类应用',
      '- **多模态** - 图文理解、视频生成',
    ]),
    related: ['AI/人工智能/深度学习实战.md'],
    backlinks: [],
  },

  'Math/数学基础/线性代数.md': {
    title: '线性代数',
    domain: 'Math',
    level: 'L1',
    status: 'published',
    quality_score: 0.91,
    version: '1.0.0',
    tags: ['线性代数', '矩阵', '向量空间'],
    body_markdown: makeBody('线性代数', [
      '## 向量与矩阵',
      '',
      '线性代数是机器学习和深度学习的数学基础。',
      '',
      '### 矩阵乘法',
      '',
      '```',
      'C = A × B',
      '',
      '其中 C[i,j] = Σ A[i,k] × B[k,j]',
      '```',
      '',
      '## 核心概念',
      '',
      '| 概念 | 说明 |',
      '|------|------|',
      '| 向量空间 | n维向量的集合 |',
      '| 特征值 | 矩阵的重要性质 |',
      '| 奇异值分解 | 数据降维技术 |',
      '',
      '## 应用',
      '',
      '- 主成分分析（PCA）',
      '- 协同过滤推荐',
      '- 图像处理与压缩',
    ]),
    related: ['Math/数学基础/概率论.md'],
    backlinks: [],
  },

  'Math/数学基础/概率论.md': {
    title: '概率论',
    domain: 'Math',
    level: 'L1',
    status: 'published',
    quality_score: 0.89,
    version: '1.0.0',
    tags: ['概率论', '统计学', '贝叶斯'],
    body_markdown: makeBody('概率论', [
      '## 基本概念',
      '',
      '概率论研究随机现象的数量规律。',
      '',
      '### 概率分布',
      '',
      '| 分布 | 应用场景 |',
      '|------|----------|',
      '| 正态分布 | 自然现象建模 |',
      '| 伯努利分布 | 二分类问题 |',
      '| 泊松分布 | 计数过程 |',
      '',
      '## 贝叶斯定理',
      '',
      '```',
      'P(A|B) = P(B|A) × P(A) / P(B)',
      '```',
      '',
      '- **先验概率** - P(A)',
      '- **似然** - P(B|A)',
      '- **后验概率** - P(A|B)',
      '',
      '## 在 ML 中的应用',
      '',
      '- 朴素贝叶斯分类器',
      '- 最大似然估计',
      '- 贝叶斯优化',
    ]),
    related: ['Math/数学基础/线性代数.md', 'AI/人工智能/机器学习基础.md'],
    backlinks: [],
  },
}