coverage:
  precision: 2
  round: down
  range: "50...90"

  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 75%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_head: yes

ignore:
  - "**/tests/**"
  - "**/benches/**"
  - "**/examples/**"
  - "**/main.rs"
  - "**/lib.rs"                  # 仅 module 声明, 无逻辑

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
      - type: patch