/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/compile/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["compile_status_path"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_path"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["index_rebuild_path"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["index_status_path"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["server_info_path"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            error: string;
        };
        ExtractionHealthHttp: {
            backends: string[];
            default_method: string;
            vlm_configured: boolean;
        };
        HealthReportHttp: {
            avg_quality_score: string;
            contradiction_count: number;
            extraction?: null | components["schemas"]["ExtractionHealthHttp"];
            graph_edges: number;
            graph_nodes: number;
            orphan_count: number;
            total_entries: number;
        };
        IndexRebuildHttp: {
            fulltext_entries_indexed: number;
            graph_edges: number;
            graph_nodes: number;
            status: string;
            vector_entries_indexed: number;
        };
        ServerInfoHttp: {
            api_catalog_size: number;
            contract_version: string;
            http_running: boolean;
            /** @description Example path for `KNOWLEDGE_BASE_PATH` in Cursor mcp.json. */
            knowledge_base_hint: string;
            manifest_sha256: string;
            mcp_config_snippet: unknown;
            /** @description MCP exposure mode: `code` (2 tools) or `full` (per-tool schemas). */
            mcp_mode: string;
            mcp_tool_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compile_status_path: {
        parameters: {
            query?: {
                /** @description Knowledge base id */
                kb_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compile job view JSON object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_path: {
        parameters: {
            query?: {
                /** @description Knowledge base id */
                kb_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReportHttp"];
                };
            };
            /** @description Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    index_rebuild_path: {
        parameters: {
            query?: {
                /** @description Knowledge base id */
                kb_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rebuild stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexRebuildHttp"];
                };
            };
            /** @description Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    index_status_path: {
        parameters: {
            query?: {
                /** @description Knowledge base id */
                kb_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Last index rebuild metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_info_path: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MCP mode and config snippet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfoHttp"];
                };
            };
        };
    };
}
